name: CODECOV_TOKEN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
    - name: Build and test with Maven
      run: mvn clean verify

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
    
